anza-xyz/alpenglow

Cargo.lock
core/Cargo.toml
core/src/staked_validators_cache.rs
core/src/voting_service.rs

Cache Alpenglow sockets and use them when pushing BLS messages in voting service.
- We will switch to QUIC or SNP in a later PR, this is just using UDP for the prototype testing
- Actually switching to BLS messages will happen in later PRs
- Once we switch to BLS messages, the original pushAlpenglowVote which sends vote transactions can be decommed

Add option to push BLS message to Alpenglow sockets in voting service.

---

core/Cargo.toml
core/src/alpenglow_consensus/certificate_pool.rs
core/src/alpenglow_consensus/transaction.rs
core/src/alpenglow_consensus/vote_certificate.rs
core/src/alpenglow_consensus/vote_pool.rs
programs/sbf/Cargo.lock
svm/examples/Cargo.lock

When we switch to BLS certificate, we will never need to copy transactions out.
We just need to iterate through the current transactions saved in vote_pool and aggregate them to the final certificates.
This saves us a lot of unnecessary copy.
Also simplify the tests a bit.

Switch from copy_out_transactions to add_to_certificate.

---

core/src/alpenglow_consensus.rs
core/src/alpenglow_consensus/block_creation_loop.rs
core/src/alpenglow_consensus/certificate_pool.rs
core/src/alpenglow_consensus/parent_ready_tracker.rs
core/src/alpenglow_consensus/voting_loop.rs
core/src/consensus/progress_map.rs
core/src/replay_stage.rs

Reuploaded from #198 
We still use the branch certified / skip certified naming from an earlier draft of the paper. Additionally we don't actually verify the hash for notarize fallback certificates.
Finally we hack in slot 1 for WFSM to enable GCE tests.
- Add parent ready tracker to explicitly track notarize fallback / skip certificates by block hashes
- Update voting loop to use parent ready instead of old checks (Note this shouldn't actually change any behavior at the moment, but will once we have duplicate blocks)
- Instead of hacking in WFSM / snapshot slots, implicitely notarize fallback the root bank used in startup
Fixes https://github.com/anza-xyz/alpenglow/issues/155

voting_loop: add parent ready tracker, fix WFSM / snapshot hack

---

core/src/alpenglow_consensus/parent_ready_tracker.rs

We update the `highest_with_parent_ready` regardless of whether we actually inserted a new parent.
This causes the `voting_loop` to progress even if there isn't actually a proper chain of notarize fallback / skip certificates up to the `highest_with_parent_ready` slot.
Although usually this isn't a problem because the certificates will eventually come in, if the node is a leader for the next window, and the certificates are coming in out of order, we could end up calling `block_production_parent` and failing:
```
thread 'solVotingLoop' panicked at core/src/alpenglow_consensus/voting_loop.rs:272:22:
Must have a block production parent in sequential voting loop
```
Only update `highest_with_parent_ready` if a higher slot actually reached `parent_ready` status, and add a test for this out of …

parent_ready: only update highest parent ready if a parent was added

---

gossip/src/main.rs
multinode-demo/bootstrap-validator.sh
net/remote/remote-node.sh
validator/src/bin/solana-test-validator.rs
validator/src/cli.rs
validator/src/commands/run/args.rs
validator/src/commands/run/execute.rs

When starting a boostrap node (no entrypoint args set) without `gossip_host` set, we will fall back to localhost IP. This causes contact info to be filtered out, and other nodes cannot join the cluster. `gossip_host` has been deprecated upstream.
This was discovered when trying to spin up Alpenglow repo on invalidator cluster (it has removed `gossip_host` arg, inline with the upstream deprecation).
Cherry pick 2 upstream fixes related to this:
https://github.com/anza-xyz/agave/commit/e218d961a14115fa09dccf5a21f10a1e1b272275
https://github.com/anza-xyz/agave/commit/de672d2a81175a866e3a947b7dbede21fe2c054d

Gossip host upstream

---

core/src/alpenglow_consensus/block_creation_loop.rs

Trying to be fancy and doing the block creation in the same loop as the transaction receive and record causes all sorts of deadlocks as:
- Consumer holds the freeze lock
- TransactionRecorder sends the record through the crossbeam channel and waits for a response
- If the PoHService does not respond, the freeze lock is held indefinitely
- This blocks the voting loop, and when creating a child block in the block creation loop
- As the block creation loop is stuck waiting for the lock, it doesn't process the record from TransactionRecorder
Instead keep it simple and run record and receive in a separate loop to ensure that the crossbeam channels are always free.
The consume worker will take work iteratively, so there will be points where the freeze lock is released.

block_creation_loop: split out record and receive to separate thread

---

Cargo.lock
Cargo.toml
validator/src/commands/run/execute.rs

Builds on #212 
Invalidator buildkite pipeline failing to fetch the `alpenglow-vote` program repo with ssh credentials.
Example of failure for invalidator pipeline:
https://buildkite.com/anza/infra-invalidator/builds/2026#01977ffa-7548-4e91-84b9-0f58257a47bd
Switch to https. This repo is public now

Vote Fetch Dependency

---

core/src/alpenglow_consensus.rs

Block time is dynamic at the moment, based  on the skip timeout.
This leads to a longer leader transition.
Instead as specified in the paper, fix this to the block time

block_creation_loop: adjust blocktime to always be 400ms

---

core/src/alpenglow_consensus/voting_loop.rs

We're keeping the wrong set of pending blocks in the voting loop, which can lead to holding old banks indefinitely and leaking mem
Keep only the pending banks ahead of the root

pending blocks orphaning

---

core/src/replay_stage.rs

We grab the write lock every replay iteration even when there are no new banks to insert.
Only grab the lock if we're actually going to insert something.

replay: do not grab bank forks write lock if no banks to insert

---

program-runtime/src/loaded_programs.rs
runtime/src/bank.rs
runtime/src/bank_forks.rs

We grab the bank forks read lock in order to call `prune_program_cache()` , which in turn grabs the read lock again. This can cause a deadlock if a writer requests the lock in between:
1) `handle_new_root` acquires the read lock in order to call prune_program_cache
2) `generate_new_bank_forks` asks for the write lock
3) `prune_program_cache` tries to acquire the read lock again during `fork_graph.read()`
4) Deadlock, as (3) will never complete due to the presence of (2)
Have `prune_program_cache` pass in `BankForks` to avoid the reentrant locking

replay: remove reentrant locking in prune program cache

---

ledger/src/blockstore/blockstore_purge.rs

The `SlotCertificates` column is never purged as part of the blockstore cleanup process.
Still don't think this is the cause of the memory leak as it shouldn't be correlated to # txs and all in disk. Forgot to do this in #178 🤦 .
Add it to the `blockstore_purge` list.

blockstore: purge slot_certificates column

---

core/src/alpenglow_consensus/voting_loop.rs
core/src/replay_stage.rs
core/src/vote_simulator.rs
core/tests/unified_scheduler.rs

Scrapping the initial plan of pruning progress from the voting loop, most of the fields are obsolete with alpenglow and the remaining ones are only useful in replay so no need to share this between both threads.
Prune progress map in replay on successful bank completion.
There's still some fields being populated like the PropagatedStats within progress map that are no longer used, but we can take care of removing them during cleanup post alpenglow.

replay: handle set_root of progress map in replay

---

core/src/alpenglow_consensus/block_creation_loop.rs
core/src/alpenglow_consensus/certificate_pool.rs
core/src/alpenglow_consensus/parent_ready_tracker.rs
core/src/alpenglow_consensus/voting_loop.rs

Implements #121
For the voting loop, I've added code that fetches the vote history for the new pubkey, if the `set-identity` was called during startup. If it was called during the main loop, I update the pubkey and fetch the vote history for the new pubkey, and update related contexts & certificate pool where the pubkey is used in.
* For the main loop, I check this before the pubkey is used, such as in the `is_leader` boolean.
For the block creation loop, I update the pubkey if `set-identity` was called during the main loop.
* For the startup of the block creation loop, the original issue mentions "If set-identity has been called during startup, update pubkey in block creation loop". I'm unsure if I'm misunderstanding, but isn't this already implemented in [line …

Handle set-identity in voting loop

---

Cargo.toml
core/src/alpenglow_consensus.rs
core/src/alpenglow_consensus/certificate_pool.rs
core/src/alpenglow_consensus/vote_pool.rs

Certificate pool doesn't allow a notarize for block b and then a notarize fallback for block b'
Update the conflicting vote check to compare block id / bank hash when dealing with 2 block based vote types

certificate pool: fix conflicting vote check for notarize fallback

---

core/src/alpenglow_consensus/voting_loop.rs
core/src/banking_simulation.rs
core/src/replay_stage.rs
core/src/tpu.rs
core/src/tvu.rs
core/src/validator.rs
ledger/src/blockstore.rs
turbine/src/broadcast_stage.rs
turbine/src/broadcast_stage/broadcast_duplicates_run.rs
turbine/src/broadcast_stage/broadcast_fake_shreds_run.rs
turbine/src/broadcast_stage/broadcast_utils.rs
turbine/src/broadcast_stage/fail_entry_verification_broadcast_run.rs
turbine/src/broadcast_stage/standard_broadcast_run.rs

We send all replayed blocks to the voting loop. Since shredding is asynchronous, replayed leader blocks might not be eligible for voting yet as the block id is missing.
This adds complexity to the voting loop which has to check blockstore and potentially update the bank with the block_id. Additionally the voting loop doesn't handle this transient condition properly , see #249 for example.
Instead we:
1. For non leader blocks, in replay we set the block id and send the completed bank to the voting loop
2. For leader blocks, instead broadcast stage will set the block id and send the completed bank
3. The voting loop now will always have the block id for any incoming banks, the blockstore fetch can be removed.
4. `try_notar` can only fail transiently for certificate checks now, refactor the …

only send block to voting loop once block_id is available

---

core/src/sigverifier/bls_sigverifier.rs
programs/sbf/Cargo.lock
svm/examples/Cargo.lock

[2025-07-12T18:01:30.524548697Z WARN  solana_metrics::metrics] submit response unsuccessful: 400 Bad Request {"error":"partial write: unable to parse 'bls_sig_verifier_stats,host_id=tiv1zkpDdumabxfZisVjuQgDzGcVSVDTEaHJD6ueVuK sent=1u,sent_failed=0u,received=1u,received_malformed=0u 1752343289602304527': invalid number dropped=0"}
Change back to i64 for now, change to u64 when it is fixed.

InfluxDB doesn't understand u64 yet.

---

Cargo.lock
local-cluster/Cargo.toml
local-cluster/src/integration_tests.rs
local-cluster/tests/local_cluster.rs

Ensure that the number of slots is a multiple of NUM_CONSECUTIVE_LEADER_SLOTS. Because we only check leadership every NUM_CONSECUTIVE_LEADER_SLOTS slots in block_creation_loop.
For example, you can have [(pubkey_A, 70), (pubkey_B, 30)], A will happily produce block 70 and 71 because it is the leader for block 68, but when B gets the shred it check leadership for block 70 and 71, it will see that itself is the leader, so the shreds from A will be ignored.
This can cause tests to fail.
Make sure the number of slots in custom_leader_schedule is always a multiple of NUM_CONSECUTIVE_LEADER_SLOTS.

Make create_custom_leader_schedule give all slots in one leader window to the same person

---

votor/src/certificate_pool.rs
votor/src/certificate_pool/vote_pool.rs
votor/src/voting_loop.rs

As part of #250 certificate pool ingest will be in a separate thread that doesn't have access to VoteHistory
Instead of using VoteHistory, use our previous votes from the pool itself. Future PR will initialize cert pool from vote history on startup.

certificate_pool: use prev vote instead of VoteHistory in safe_to_*

---

votor/src/vote_history.rs

For use in #250 voting loop doesn't need full access to the certificate pool, instead it can store these events in vote history.
Additionally on restart it's useful to have these values ready as we don't persist the certificate pool.
Similar to the paper store BlockNotarized and ParentReady in vote history for permanent storage.

vote history: add block notarized and parent ready

---

votor/src/certificate_pool.rs
votor/src/certificate_pool/vote_pool.rs

Vote pools use Option<BankId>, Option<BankHash>  to distinguish between notarize/non-notarize pools, making all the API's hard to digest and error-prone if people pass in the wrong options.
Two different types of pools, `DuplicateBlockVotePool` that can take multiple votes per validator and `SimpleVotePool` that can't. 
Next steps could make a typed pool for each of the 5 different types of pools in `vote_pools: BTreeMap<PoolId, VotePoolType>,` so that each vote type has an explicitly typed pool of either `DuplicateBlockVotePool` or `SimpleVotePool`
Fixes #

Statically type vote pools 

---

core/src/replay_stage.rs
core/src/tvu.rs
core/src/validator.rs
votor/src/certificate_pool_service.rs
votor/src/event_handler.rs
votor/src/votor.rs

We maintain a separate receiver for our own votes.
We maintain a separate receiver for skip timeout events.
Unify it all so bls messages come through one receiver, and event messages come through one receiver.
Takes care of https://github.com/anza-xyz/alpenglow/pull/279#discussion_r2224134357
If we want to handle our own votes separately, we can add an enum later.

votor: unify own vote sender with bls receiver, unify skip receiver

---

votor/src/certificate_pool_service.rs
votor/src/voting_utils.rs

Move this to certificate pool service. Takes care of https://github.com/anza-xyz/alpenglow/pull/279#discussion_r2224133562

refactor: move add_message_and_maybe_update_commitment out of vote_utils

---

core/src/block_creation_loop.rs
core/src/repair/certificate_service.rs
ledger/src/blockstore.rs
ledger/src/blockstore_meta.rs
local-cluster/tests/local_cluster.rs
votor/src/certificate_pool.rs
votor/src/certificate_pool/parent_ready_tracker.rs
votor/src/certificate_pool/vote_certificate.rs
votor/src/certificate_pool/vote_pool.rs
votor/src/certificate_pool_service.rs
votor/src/event.rs
votor/src/event_handler.rs
votor/src/lib.rs
votor/src/root_utils.rs
votor/src/vote_history.rs

Follow up to https://github.com/anza-xyz/alpenglow/pull/264
Bank hashes no longer necessary to identify blocks, block ids are sufficient
Remove bank hashes everywhere except in places that touch the separate alpenglow vote crate, those need to be updated separately
Fixes #

Remove bank hash from Alpenglow structures

---

core/src/cluster_info_vote_listener.rs

- Use `let Some` bindings instead of checking for `Some` and then `unwrap`ing.
- Remove a function that performs a trivial computation and associated tests.

refactor: minor cleanups

---

votor/src/certificate_pool_service.rs

Currently highest_finalized_slot is just used to:
1. check whether the returned `highest_finalized_slot` is larger than the local copy, which `certificate_pool` already checks before returning
2. used in `Standstill` event creation, here we can actually get the value from `cert_pool.highest_finalized_slot()`.
So we can remove the local `highest_finalized_slot`, makes the code a bit simpler.

Replace local highest_finalized_slot with pool.highest_finalized_slot.

---

ledger/src/leader_schedule_utils.rs
votor/src/skip_timer.rs

https://github.com/anza-xyz/alpenglow/issues/303
Fixes #

Add remaining window slots util

---

.buildkite/alpenglow/pipeline.sh
ci/stable/run-partition.sh

our ci is very close to the timeout.
- split it into 3
- exclude solana-cargo-build-sbf since we won't touch the logic in Alpenglow. (any errors will still be caught when submitting a PR back to Agave)

improve ci

---

votor/src/certificate_pool.rs
votor/src/certificate_pool/slot_stake_counters.rs
votor/src/certificate_pool/vote_pool.rs

We used to check safe_to_notar and safe_to_skip on every vote, there are two problems:
1. Too many unnecessary checks, we don't need to check them until at least I voted or we got new Notarize/Skip votes
2. We repeatedly send out the same event upstream, these events should only be sent once
Added SlotStakeCounters to update internal state on only corresponding votes.

Refactor safe_to_notar and safe_to_skip into SlotStakeCounters.

---

votor/src/certificate_pool_service.rs
votor/src/lib.rs
votor/src/skip_timer.rs

Updates some timeout names to be closer to what is used in the alpenglow paper.
Part of #243.

refactor: use similar terminology as the paper for timeout values

---

core/src/sigverifier/bls_sigverifier.rs
core/src/sigverifier/bls_sigverifier/stats.rs
programs/sbf/Cargo.lock
svm/examples/Cargo.lock

We could have many discarded packets, for example, when the same cert is being forwarded by several sources, deduper will mark the late ones discarded.
They will currently fail with this error message:
Failed to deserialize BLS message: the size limit has been reached
Then they will be counted as malformed packets, this is confusing, we should count discarded packets separately in stats.

Put discarded packets in stats separately.

---

core/src/block_creation_loop.rs

Solves #122 for the block creation loop by adding in metrics to track the metrics in [this comment](https://github.com/anza-xyz/alpenglow/issues/122#issuecomment-3047284188).
In this PR, I add two types of metrics for the block creation loop. `BlockCreationLoopMetrics` which provides high-level performance monitoring for the entire block creation loop, and `SlotMetrics` which provides granular monitoring for individual slot production attempts inside of the block creation loop.
---
These metrics provides high-level performance monitoring for the entire block creation loop.
| Metric | Type | Description |
|--------|---------|----------|
| `loop_count` | Counter | Total number of leader windows processed |
| `window_production_elapsed` | Duration | Total time spent producing all the slots …

block_creation_loop: add metrics

---

core/src/repair/malicious_repair_handler.rs
core/src/repair/repair_handler.rs
core/src/repair/repair_service.rs
core/src/repair/serve_repair.rs
core/src/repair/standard_repair_handler.rs
ledger/src/blockstore.rs

We need to be able to fetch alternate versions of a block and store them in the appropriate blockstore columns
Create a block id based version of orphan, highest shred, and shred, and plug in the responder.
Unlike TowerBFT the responder only fulfills these requests if it has the *complete* block for the shred(s) that are being requested.

repair: add new block_id based repair variants

---

core/src/voting_service.rs

`Option<&Vec<_>>` is a bit unergonomic to work with.
Pass `additional_listeners` as a simple slice instead.

refactor: simplify the type for `additional_listeners`

---

runtime/src/bank/serde_snapshot.rs
runtime/src/epoch_stakes.rs

This is a derived map, initialize on first use.

Do not serialize/deserialize bls_pubkey_to_rank_map.

---

core/src/sigverifier/bls_sigverifier.rs
votor-messages/src/consensus_message.rs

The certificate-to-vote conversion functions that currently exists in the bls sigverifier module more naturally belongs to the `solana-votor-messages` crate.
I refactored the certificate-to-vote conversion function from the bls sigverifier to votor-messages.
Fixes #

[bls-sigverifier, votor-messages] Refactor certificate-to-vote conversion function from bls sigverifier to votor-messages

---

core/src/sigverifier/bls_sigverifier.rs
core/src/sigverifier/bls_sigverifier/stats.rs

Skip verifying these votes/certs:
- Any vote or cert with slot not greater than root slot
- Any cert which has been previously verified
On our 50 nodes cluster:
Before this PR: Every 10 seconds we verify 52 batches of votes, 50 batches of certs
After this PR: Every 10 seconds we verify 39 batches of votes, 3.5 batches of certs

Skip verifying old votes/certs and certs which have been verified.

---

votor/src/event_handler.rs
votor/src/event_handler/stats.rs

`send_vote_time` is a misleading name since it indicates the time it took to send a single vote.
This is rather a vector of votes in the way this is implemented
Rename `send_vote_time` to `send_votes_batch_time`

Rename send_vote_time_us to send_votes_batch_time_us

---

core/Cargo.toml
core/benches/bls_sigverify.rs

I used the logs in the current alpenglow test cluster re-organize the batches for testing in the bls-sigverify bench logic.
I first attempted to hard-code some of the vote and certificate batches in the benches, but it was hard to set up the test because the vote and certificate messages do not contain the actual validator keypairs. So I updated the code so that the bench logic freshly generates vote and certificate messages that model the batch of votes and certificate messages seen commonly in the logs.

[core] Re-organize batches for bls-sigverify bench

---

votor/src/consensus_metrics.rs

instead of clearing the leader and node metrics, we were clearing the node metrics multiple times.

bug: the code was clearing the same metrics multiple times

---

core/src/commitment_service.rs
votor/src/commitment.rs
votor/src/consensus_pool.rs
votor/src/consensus_pool_service.rs
votor/src/event_handler.rs
votor/src/voting_utils.rs
votor/src/votor.rs

We renamed AlpenglowCommitment to Commitment when upstreaming to Agave, should do the same here.

Rename AlpenglowCommitment to Commitment to keep in sync with Agave.

---

votor/src/consensus_pool.rs
votor/src/consensus_pool_service.rs
votor/src/event_handler.rs
votor/src/voting_utils.rs
votor/src/votor.rs

https://anza-xyz.slack.com/archives/C06GZ20BPQB/p1759399012138259?thread_ts=1759232075.506819&cid=C06GZ20BPQB also contains more information.
This PR does the following:
- does not start the the next slot when the finalization cert for the current slot is seen as this is too early.
- only records `block_hash_seen` for the first slot in the window as for the other slots, the metric should be approximately 0
- previously a node was only recording its own vote.  Moved the vote recording to a different place where hopefully it will record votes from all nodes including self

feat: improvements to `ConsensusMetrics` based on observed data

---

votor/src/consensus_pool_service.rs
votor/src/consensus_pool_service/stats.rs

Replace u16/u32/u64 with Saturating<usize> so we can get rid of incr functions.

Replace numbers in consensus_pool_service stats with Saturating<usize>.
